name: Build and deploy a container image to Azure App service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with the Docker registry
        uses: azure/docker-login@v1
        with:
          login-server: p2pdocker.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the image tagged with the git commit hash
        run: |
          docker build . -t p2pdocker.azurecr.io/p2pdocker:${{ github.sha }}
          docker push p2pdocker.azurecr.io/p2pdocker:${{ github.sha }}

      - name: Update image tag on the Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'p2pdocker'
          slot-name: 'production'
          images: 'p2pdocker.azurecr.io/p2pdocker:${{ github.sha }}'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRODUCTION }}
